force-app/main/default/objects/Nepal_Price_List__c/Nepal_Price_List__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Nepal Price List</label>
</CustomObject>

force-app/main/default/objects/Nepal_Price_List__c/fields/Fine__c.field-meta.xml
<CustomField>
    <fullName>Fine__c</fullName>
    <label>קנס לא תקין</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>תשלום</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>תשלומים</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/index__c.field-meta.xml
<CustomField>
    <fullName>index__c</fullName>
    <label>index</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/masof__c.field-meta.xml
<CustomField>
    <fullName>masof__c</fullName>
    <label>masof</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Parent_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Parent_Transaction__c</fullName>
    <label>Parent Transaction</label>
    <referenceTo>Transaction_Card__c</referenceTo>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Time__c.field-meta.xml
<CustomField>
    <fullName>Payment_Time__c</fullName>
    <label>Payment Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Payment_Transaction_ID__c</fullName>
    <inlineHelpText>מספר אישור מחברת האשראי</inlineHelpText>
    <label>Payment Transaction ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Sum__c.field-meta.xml
<CustomField>
    <fullName>Sum__c</fullName>
    <label>Sum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/Transaction_Card__c.object-meta.xml
<CustomObject>
    <label>כרטיס עסקה</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>שם כרטיס עסקה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>כרטיס עסקה</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Card__c/fields/Account_Addressing__c.field-meta.xml
<CustomField>
    <fullName>Account_Addressing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>פונה</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>עסקאות</relationshipLabel>
    <relationshipName>Transaction_Card</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/CC_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>CC_Expiration_Date__c</fullName>
    <label>CC Expiration Date</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Cost_Calculated_Planned_N__c.field-meta.xml
<CustomField>
    <fullName>Cost_Calculated_Planned_N__c</fullName>
    <label>עלות מחושבת מתוכנן</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Device__c.field-meta.xml
<CustomField>
    <fullName>Device__c</fullName>
    <label>מכשיר</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>מכשיר A</label>
            </value>
            <value>
                <fullName>SE+</fullName>
                <label>מכשיר SE+</label>
            </value>
            <value>
                <fullName>Mini</fullName>
                <label>מכשיר  mini</label>
            </value>
            <value>
                <fullName>MINI 2</fullName>
            </value>
            <value>
                <fullName>A - מטיילים בחול</fullName>
            </value>
            <value>
                <fullName>A - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>MINI - מטיילים בחול</fullName>
            </value>
            <value>
                <fullName>MINI - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>Iridium 9555</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>Messenger</fullName>
            </value>
            <value>
                <fullName>MINI 2 - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>MINI 2 - מטיילים בחו&quot;ל</fullName>
            </value>
            <value>
                <fullName>Messenger - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>Messenger - מטיילים בחו&quot;ל</fullName>
            </value>
            <value>
                <fullName>SE+ - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>SE+ - מטיילים בחו&quot;ל</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Token_Id__c.field-meta.xml
<CustomField>
    <fullName>Token_Id__c</fullName>
    <label>Token Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/TookFine__c.field-meta.xml
<CustomField>
    <fullName>TookFine__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TookFine</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NepalFinesQueue.cls
public without sharing class NepalFinesQueue implements Queueable, Database.AllowsCallouts {
	public List <Transaction_Card__c> tcs;
	public NepalFinesQueue(List <Transaction_Card__c> ts) {
		tcs=ts;
	}
	public void execute(QueueableContext context) {
		/*if(tcs.size()>0){
			Transaction_Card__c tcc=tcs[0];
			Nepal_Price_List__c	npl=[select Fine__c from Nepal_Price_List__c Where Device__c=:tcc.Device__c];
			Decimal Price=npl.Fine__c.setScale(2);
			Http http=new Http();
			HttpRequest req=new HttpRequest();
			req.setendpoint('https://secure5.tranzila.com/cgi-bin/tranzila71u.cgi');
			req.setmethod('POST');
			string pos='supplier=magnusintetok&sum='+Price+'&expdate='+tcc.CC_Expiration_Date__c+'&currency=2&TranzilaPW=zJkelm&TranzilaTK='+tcc.Token_id__c+'&cred_type=1&tranmode=A&SF_Transaction_Id='+tcc.id+'&contact='+tcc.Account_Addressing__r.name+'&email='+tcc.Account_Addressing__r.PersonEmail+'&phone='+tcc.Account_Addressing__r.PersonMobilePhone;
			req.setbody(pos);
			HttpResponse res;
			String str='';
			if(tcc.Token_Id__c!='testspec'){
				res = http.send(req);
				str=res.getbody();
			}
			else
				str='test&Response=000&ConfirmationCode=100&index=1&';
			if(str.contains('Response=000')){
				string con='';
				string ind='';
				String [] spl1=str.split('ConfirmationCode=');
				String [] spl2=str.split('index=');
				if(spl1[1].contains('&')){
					String [] spl3=spl1[1].split('&');
					con=spl3[0];
				}
				else
					con=spl1[1];
				if(spl2[1].contains('&')){
					String [] spl4=spl2[1].split('&');
					ind=spl4[0];
				}
				else
					ind=spl2[1];
				Payment__c pay=new Payment__c();
				pay.Parent_Transaction__c=tcc.id;
				pay.Expiration_Date__c =tcc.CC_Expiration_Date__c;
				pay.Token__c=tcc.Token_Id__c;
				pay.Result__c='000';
				pay.Payment_Transaction_ID__c=con;
				pay.index__c=ind;
				pay.masof__c='magnusintetok';
				TimeZone tz = TimeZone.getTimeZone('Asia/Jerusalem');
				DateTime localTime = System.now().AddSeconds(tz.getOffset(System.now())/1000);
				pay.Payment_Time__c=localTime;
				pay.Sum__c=Price;
				insert pay;
				tcc.TookFine__c=true;
				tcc.Cost_Calculated_Planned_N__c+=Price;
				update tcc;
			}
			tcs.remove(0);
			if(!Test.isRunningTest())
				ID jobID = System.enqueueJob(new NepalFinesQueue(tcs));
		}*/
	}
}