force-app/main/default/objects/Account/fields/Account_Mail__c.field-meta.xml
<CustomField>
    <fullName>Account_Mail__c</fullName>
    <label>Account Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Addressee_Email1__c.field-meta.xml
<CustomField>
    <fullName>Addressee_Email1__c</fullName>
    <label>נמען - דוא&quot;ל</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Addressee_First_Name1__c.field-meta.xml
<CustomField>
    <fullName>Addressee_First_Name1__c</fullName>
    <label>נמען  שם פרטי</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Addressee_First_Name2__c.field-meta.xml
<CustomField>
    <fullName>Addressee_First_Name2__c</fullName>
    <label>נמען נוסף שם פרטי</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Addressee_Last_Name1__c.field-meta.xml
<CustomField>
    <fullName>Addressee_Last_Name1__c</fullName>
    <label>נמען שם משפחה</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Addressee_phone1__c.field-meta.xml
<CustomField>
    <fullName>Addressee_phone1__c</fullName>
    <label>נמען - נייד</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Addressee_ProximityNew1__c.field-meta.xml
<CustomField>
    <fullName>Addressee_ProximityNew1__c</fullName>
    <label>נמען - קירבה</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>הפונה הוא הנוסע</fullName>
            </value>
            <value>
                <fullName>אמא/אבא</fullName>
            </value>
            <value>
                <fullName>אחות/אח</fullName>
            </value>
            <value>
                <fullName>בת/בן זוג</fullName>
            </value>
            <value>
                <fullName>חבר/ה</fullName>
            </value>
            <value>
                <fullName>אחר</fullName>
            </value>
            <value>
                <fullName>בת\בן</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Contaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Contaction_Status__c</fullName>
    <label>קשר פונה נוסע</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>הפונה הוא הנוסע</fullName>
            </value>
            <value>
                <fullName>אמא/אבא</fullName>
            </value>
            <value>
                <fullName>אחות/אח</fullName>
            </value>
            <value>
                <fullName>בת/בן זוג</fullName>
            </value>
            <value>
                <fullName>חבר/ה</fullName>
            </value>
            <value>
                <fullName>אחר</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/First_Name_English__c.field-meta.xml
<CustomField>
    <fullName>First_Name_English__c</fullName>
    <label>שם פרטי באנגלית</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Get_To_magnus__c.field-meta.xml
<CustomField>
    <fullName>Get_To_magnus__c</fullName>
    <label>איך הגעתי למגנוס</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>שמעתי מחבר</fullName>
            </value>
            <value>
                <fullName>מצאתי באינטרנט</fullName>
            </value>
            <value>
                <fullName>ראיתי בפייסבוק</fullName>
            </value>
            <value>
                <fullName>קראתי בעיתון</fullName>
            </value>
            <value>
                <fullName>ראיתי בטלויזיה</fullName>
            </value>
            <value>
                <fullName>שמעתי ברדיו</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company__c</fullName>
    <label>חברת ביטוח</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>מגדל</fullName>
            </value>
            <value>
                <fullName>הפניקס</fullName>
            </value>
            <value>
                <fullName>AIG</fullName>
            </value>
            <value>
                <fullName>ביטוח ישיר</fullName>
            </value>
            <value>
                <fullName>פספורטכארד</fullName>
            </value>
            <value>
                <fullName>הראל</fullName>
            </value>
            <value>
                <fullName>כלל</fullName>
            </value>
            <value>
                <fullName>טרם נקבע</fullName>
            </value>
            <value>
                <fullName>שירביט</fullName>
            </value>
            <value>
                <fullName>מנורה</fullName>
            </value>
            <value>
                <fullName>הכשרה</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Name_English__c.field-meta.xml
<CustomField>
    <fullName>Last_Name_English__c</fullName>
    <label>שם משפחה באנגלית</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Male_Female__c.field-meta.xml
<CustomField>
    <fullName>Male_Female__c</fullName>
    <label>מין</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>זכר</fullName>
            </value>
            <value>
                <fullName>נקבה</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Passenger_Id__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Id__c</fullName>
    <label>הנוסע-ת.זהות</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Passenger_Mail__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Mail__c</fullName>
    <label>הנוסע-דוא&quot;ל</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/PriceList__c/PriceList__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Price List</label>
</CustomObject>

force-app/main/default/objects/PriceList__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>במלאי</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PriceList__c/fields/Device__c.field-meta.xml
<CustomField>
    <fullName>Device__c</fullName>
    <label>מכשיר</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PriceList__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>מחיר</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PriceList__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>עדיפות</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PriceList__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>תוכנית</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/Transaction_Card__c.object-meta.xml
<CustomObject>
    <label>כרטיס עסקה</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>שם כרטיס עסקה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>כרטיס עסקה</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Card__c/fields/Account_Addressing__c.field-meta.xml
<CustomField>
    <fullName>Account_Addressing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>פונה</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>עסקאות</relationshipLabel>
    <relationshipName>Transaction_Card</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Account_Passenger__c.field-meta.xml
<CustomField>
    <fullName>Account_Passenger__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>נוסע</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>כרטיס עסקה</relationshipLabel>
    <relationshipName>Account_Passenger</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Date_Of_Delivery_Device__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Delivery_Device__c</fullName>
    <label>תאריך איסוף המכשיר</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Date_Of_Return__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Return__c</fullName>
    <label>תאריך חזרה לארץ</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Date_Trip__c.field-meta.xml
<CustomField>
    <fullName>Date_Trip__c</fullName>
    <label>תאריך הנסיעה</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Device__c.field-meta.xml
<CustomField>
    <fullName>Device__c</fullName>
    <label>מכשיר</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>מכשיר A</label>
            </value>
            <value>
                <fullName>SE+</fullName>
                <label>מכשיר SE+</label>
            </value>
            <value>
                <fullName>Mini</fullName>
                <label>מכשיר  mini</label>
            </value>
            <value>
                <fullName>MINI 2</fullName>
            </value>
            <value>
                <fullName>A - מטיילים בחול</fullName>
            </value>
            <value>
                <fullName>A - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>MINI - מטיילים בחול</fullName>
            </value>
            <value>
                <fullName>MINI - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>Iridium 9555</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>Messenger</fullName>
            </value>
            <value>
                <fullName>MINI 2 - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>MINI 2 - מטיילים בחו&quot;ל</fullName>
            </value>
            <value>
                <fullName>Messenger - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>Messenger - מטיילים בחו&quot;ל</fullName>
            </value>
            <value>
                <fullName>SE+ - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>SE+ - מטיילים בחו&quot;ל</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company__c</fullName>
    <label>Insurance</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>מגדל</fullName>
            </value>
            <value>
                <fullName>AIG</fullName>
            </value>
            <value>
                <fullName>ביטוח ישיר</fullName>
            </value>
            <value>
                <fullName>פספורטכארד</fullName>
            </value>
            <value>
                <fullName>הפניקס</fullName>
            </value>
            <value>
                <fullName>הראל</fullName>
            </value>
            <value>
                <fullName>כלל</fullName>
            </value>
            <value>
                <fullName>טרם נקבע</fullName>
            </value>
            <value>
                <fullName>שירביט</fullName>
            </value>
            <value>
                <fullName>מנורה</fullName>
            </value>
            <value>
                <fullName>הכשרה</fullName>
            </value>
            <value>
                <fullName>ביטוח חקלאי</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Passenger_Id__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Id__c</fullName>
    <formula>Account_Passenger__r.Passenger_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>הנוסע-ת.זהות</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>עדיפות תוכנית</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>תוכנית</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Magnus Basic</fullName>
            </value>
            <value>
                <fullName>Magnus Advanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Record_Type_Name_Text__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name_Text__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type Name Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Scheduled_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Return_Date__c</fullName>
    <label>תאריך החזרה מתוכנן</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Track_s__c.field-meta.xml
<CustomField>
    <fullName>Track_s__c</fullName>
    <label>Track(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AssemblyController.cls
public without sharing class AssemblyController {
    Public id Curid;
    Public Transaction_Card__c tcc {get;set;}
    Public Account accadd {get;set;}
    Public Account accpas {get;set;}
    Public AssemblyParameters__c asp {get;set;}
    public String Device {get;set;}
    public String seplus;
    public String type;
    public List <PriceList__c> A {get;set;}
    public List <PriceList__c> SEP {get;set;}
    public AssemblyController(ApexPages.StandardController controller){
        Device='';
        seplus = Label.SEplus;
        CurId = ApexPages.currentPage().getParameters().get('id');
        A=[select Price__c,Available__c from PriceList__c Where Device__c='A' And Program__c='Magnus Basic' Order by Priority__c];
        SEP=[select Price__c,Available__c from PriceList__c Where Device__c='SE+' And Program__c='Magnus Basic' Order by Priority__c];
        tcc=[Select id,Date_Of_Delivery_Device__c,Scheduled_Return_Date__c,Record_Type_Name_Text__c,Passport_Number__c,Track_s__c,Insurance_Company__c,Date_Trip__c,Date_Of_Return__c,Account_Passenger__c,Account_Addressing__c,Device__c from Transaction_Card__c where id=:Curid];
        if(tcc.Device__c!=null)
            Device=tcc.Device__c;
        System.debug(tcc.Record_Type_Name_Text__c);
        if(tcc.Record_Type_Name_Text__c==null||tcc.Record_Type_Name_Text__c=='לוויני')
            type='Default';
        else if(tcc.Record_Type_Name_Text__c=='נפאל')
            type='Nepal';
        System.debug(type);
        accadd=[select id,Firstname,Lastname,Phone,PersonEmail,Account_Mail__c,Get_To_magnus__c,Contaction_Status__c from account where id=:tcc.Account_Addressing__c];
        accpas=[select id,Firstname,Lastname,PersonEmail,Male_Female__c,PersonBirthdate,First_Name_English__c,Last_Name_English__c,Phone,Passenger_Mail__c,PersonHomePhone,BillingCity,BillingStreet,BillingCountry,BillingPostalCode,Passenger_Id__c,Addressee_First_Name1__c,Addressee_Last_Name1__c,Addressee_Email1__c,Addressee_phone1__c,Addressee_ProximityNew1__c,Addressee_First_Name2__c,Addressee_Last_Name2__c,Addressee_Email2__c,Addressee_phone2__c,Addressee_ProximityNew2__c from account where id=:tcc.Account_Passenger__c];
        asp=[select Form_URL__c from AssemblyParameters__c where name=:type];
    }
    public PageReference CheckFirst(){
        if(Device!=''||seplus!='TRUE'){
            String url=Tran();
            PageReference pageRef = new PageReference(url);
            pageref.setRedirect(true);
            return pageRef;
        }
        else
            return null;
    }
    public PageReference Redirect(){
        String url=Tran();
        PageReference pageRef = new PageReference(url);
        pageref.setRedirect(true);
        return pageRef;
    }
    public String Tran(){
        string abc='aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ';
        string DateDep='';
        string DateBack='';
        string DateBirth='';
        if(type=='Default'){
            if(tcc.Date_Trip__c!=null)
                DateDep=tcc.Date_Trip__c.format();
            if(tcc.Date_Of_Return__c!=null)
                DateBack=tcc.Date_Of_Return__c.format();
        }
        if(type=='Nepal'){
            if(tcc.Date_Of_Delivery_Device__c!=null)
                DateDep=tcc.Date_Of_Delivery_Device__c.format();
            if(tcc.Scheduled_Return_Date__c!=null)
                DateBack=tcc.Scheduled_Return_Date__c.format();
        }
        if(accpas.PersonBirthdate!=null)
            DateBirth=accpas.PersonBirthdate.format();
        String url=asp.Form_URL__c+'?'+
            'tfa_2899='+tcc.id+
            '&tfa_2889='+(tcc.Insurance_Company__c!=null?tcc.Insurance_Company__c:'')+
            '&tfa_3605='+DateDep+
            '&tfa_3606='+DateBack+
            '&tfa_2897='+accadd.id+
            '&tfa_1876='+(accadd.FirstName!=null?accadd.FirstName:'')+
            '&tfa_1='+(accadd.LastName!=null?accadd.LastName:'')+
            '&tfa_1873='+(accadd.PersonEmail!=null?accadd.PersonEmail:'')+
            '&tfa_1880='+(accadd.Phone!=null?accadd.Phone:'')+
            '&tfa_2874='+(accadd.Get_To_magnus__c!=null?accadd.Get_To_magnus__c:'')+
            '&tfa_2882='+(accadd.Contaction_Status__c!=null?accadd.Contaction_Status__c:'')+
            '&tfa_2898='+accpas.id+
            '&tfa_1926='+((accpas.FirstName!=null&&(accpas.FirstName.containsany(abc)))?accpas.FirstName:'')+
            '&tfa_1928='+((accpas.LastName!=null&&(accpas.LastName.containsany(abc)))?accpas.LastName:'')+
            '&tfa_1917='+(accpas.Male_Female__c!=null?accpas.Male_Female__c:'')+
            '&tfa_1921='+DateBirth+
            '&tfa_1884='+((accpas.FirstName!=null&&(!accpas.FirstName.containsany(abc)))?accpas.FirstName:accpas.First_Name_English__c)+
            '&tfa_1885='+((accpas.LastName!=null&&(!accpas.LastName.containsany(abc)))?accpas.LastName:accpas.Last_Name_English__c)+
            '&tfa_1930='+(accpas.Phone!=null?accpas.Phone:'')+
            '&tfa_1931='+(accpas.PersonEmail!=null?accpas.PersonEmail:'')+
            '&tfa_1933='+(accpas.PersonHomePhone!=null?accpas.PersonHomePhone:'')+
            '&tfa_2197='+(accpas.BillingCity!=null?accpas.BillingCity:'')+
            '&tfa_2195='+(accpas.BillingStreet!=null?accpas.BillingStreet:'')+
            '&tfa_2198='+(accpas.BillingCountry!=null?accpas.BillingCountry:'')+
            '&tfa_2509='+(accpas.BillingPostalCode!=null?accpas.BillingPostalCode:'')+
            '&tfa_2902='+(accpas.Addressee_First_Name1__c!=null?accpas.Addressee_First_Name1__c:'')+
            '&tfa_2904='+(accpas.Addressee_Last_Name1__c!=null?accpas.Addressee_Last_Name1__c:'')+
            '&tfa_2907='+(accpas.Addressee_Email1__c!=null?accpas.Addressee_Email1__c:'')+
            '&tfa_2906='+(accpas.Addressee_phone1__c!=null?accpas.Addressee_phone1__c:'')+
            '&tfa_3608='+(accpas.Addressee_ProximityNew1__c!=null?accpas.Addressee_ProximityNew1__c:'')+
            '&tfa_2920='+(accpas.Addressee_First_Name2__c!=null?accpas.Addressee_First_Name2__c:'')+
            '&tfa_2921='+(accpas.Addressee_Last_Name2__c!=null?accpas.Addressee_Last_Name2__c:'')+
            '&tfa_2924='+(accpas.Addressee_Email2__c!=null?accpas.Addressee_Email2__c:'')+
            '&tfa_3629='+DateBack+
            '&tfa_2923='+(accpas.Addressee_phone2__c!=null?accpas.Addressee_phone2__c:'')+
            '&tfa_3631='+(accadd.PersonEmail!=null?accadd.PersonEmail:'')+
            '&tfa_3615='+(accpas.Addressee_ProximityNew2__c!=null?accpas.Addressee_ProximityNew2__c:'')+
            '&tfa_3645='+Device+
            (type=='Default'?('&tfa_2513='+(accpas.Passenger_Id__c!=null?accpas.Passenger_Id__c:'')):('&tfa_2513='+(tcc.Passport_Number__c!=null?tcc.Passport_Number__c:'')+'&tfa_2516='+(tcc.Track_s__c!=null?tcc.Track_s__c:'')));
        return url;
    }
}