force-app/main/default/objects/Affiliate__c/Affiliate__c.object-meta.xml
<CustomObject>
    <label>שותפים</label>
    <nameField>
        <label>שותפים Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainings__c/Trainings__c.object-meta.xml
<CustomObject>
    <label>כרטיס הדרכה</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>מספר הדרכה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>כרטיס הדרכות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trainings__c/fields/Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_Time__c</fullName>
    <inlineHelpText>נא לשים לב שהתאריך והשעה תקין!</inlineHelpText>
    <label>מועד</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trainings__c/fields/Device__c.field-meta.xml
<CustomField>
    <fullName>Device__c</fullName>
    <label>Device</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SE+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/Transaction_Card__c.object-meta.xml
<CustomObject>
    <label>כרטיס עסקה</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>שם כרטיס עסקה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>כרטיס עסקה</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Card__c/fields/Account_Addressing__c.field-meta.xml
<CustomField>
    <fullName>Account_Addressing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>פונה</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>עסקאות</relationshipLabel>
    <relationshipName>Transaction_Card</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/AddressForDelivery__c.field-meta.xml
<CustomField>
    <fullName>AddressForDelivery__c</fullName>
    <label>כתובת למשלוח</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Affiliate__c.field-meta.xml
<CustomField>
    <fullName>Affiliate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>שותף</label>
    <referenceTo>Affiliate__c</referenceTo>
    <relationshipLabel>כרטיס עסקה</relationshipLabel>
    <relationshipName>Transaction_Card</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/BatAmount__c.field-meta.xml
<CustomField>
    <fullName>BatAmount__c</fullName>
    <defaultValue>10</defaultValue>
    <label>מחיר סוללה</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/CC_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>CC_Expiration_Date__c</fullName>
    <label>CC Expiration Date</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/CityForDelivery__c.field-meta.xml
<CustomField>
    <fullName>CityForDelivery__c</fullName>
    <label>ישוב למשלוח</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Cost_Calculated_Planned_N__c.field-meta.xml
<CustomField>
    <fullName>Cost_Calculated_Planned_N__c</fullName>
    <label>עלות מחושבת מתוכנן</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Date_Of_Delivery_Device__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Delivery_Device__c</fullName>
    <label>תאריך איסוף המכשיר</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Days_Of_Planned_Service__c.field-meta.xml
<CustomField>
    <fullName>Days_Of_Planned_Service__c</fullName>
    <formula>Scheduled_Return_Date__c -Date_Of_Delivery_Device__c + 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>מס&apos; ימי שירות מתוכנן</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <defaultValue>false</defaultValue>
    <label>משלוח</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/DeliveryCost__c.field-meta.xml
<CustomField>
    <fullName>DeliveryCost__c</fullName>
    <label>עלות משלוח</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Device__c.field-meta.xml
<CustomField>
    <fullName>Device__c</fullName>
    <label>מכשיר</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>מכשיר A</label>
            </value>
            <value>
                <fullName>SE+</fullName>
                <label>מכשיר SE+</label>
            </value>
            <value>
                <fullName>Mini</fullName>
                <label>מכשיר  mini</label>
            </value>
            <value>
                <fullName>MINI 2</fullName>
            </value>
            <value>
                <fullName>A - מטיילים בחול</fullName>
            </value>
            <value>
                <fullName>A - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>MINI - מטיילים בחול</fullName>
            </value>
            <value>
                <fullName>MINI - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>Iridium 9555</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>Messenger</fullName>
            </value>
            <value>
                <fullName>MINI 2 - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>MINI 2 - מטיילים בחו&quot;ל</fullName>
            </value>
            <value>
                <fullName>Messenger - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>Messenger - מטיילים בחו&quot;ל</fullName>
            </value>
            <value>
                <fullName>SE+ - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>SE+ - מטיילים בחו&quot;ל</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/discount__c.field-meta.xml
<CustomField>
    <fullName>discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>הנחה</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Dollar_Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>Dollar_Exchange_Rate__c</fullName>
    <defaultValue>3.55</defaultValue>
    <label>שער דולר</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/lithium__c.field-meta.xml
<CustomField>
    <fullName>lithium__c</fullName>
    <defaultValue>1</defaultValue>
    <label>כמות סוללות ליתיום</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Manual_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Manual_Transaction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>עסקה ידנית</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Maximum_Allowed_Num_Payments__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Allowed_Num_Payments__c</fullName>
    <label>Maximum Allowed Num Payments</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/No_of_Payments__c.field-meta.xml
<CustomField>
    <fullName>No_of_Payments__c</fullName>
    <label>מספר תשלומים בפועל(מכשיר)</label>
    <summaryFilterItems>
        <field>Payment__c.VAT_payment__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Payment__c.Parent_Transaction__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>תוכנית</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Magnus Basic</fullName>
            </value>
            <value>
                <fullName>Magnus Advanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Rec_Bat_Amount__c.field-meta.xml
<CustomField>
    <fullName>Rec_Bat_Amount__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Rec Bat Amount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Scheduled_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Return_Date__c</fullName>
    <label>תאריך החזרה מתוכנן</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Step_Price1__c.field-meta.xml
<CustomField>
    <fullName>Step_Price1__c</fullName>
    <label>מחיר מדרגה 1</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Step_Price2__c.field-meta.xml
<CustomField>
    <fullName>Step_Price2__c</fullName>
    <label>מחיר מדרגה 2</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Step_Price3__c.field-meta.xml
<CustomField>
    <fullName>Step_Price3__c</fullName>
    <label>מחיר מדרגה 3</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Step_Price4__c.field-meta.xml
<CustomField>
    <fullName>Step_Price4__c</fullName>
    <label>מחיר מדרגה 4</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Step_Size1__c.field-meta.xml
<CustomField>
    <fullName>Step_Size1__c</fullName>
    <label>גודל מדרגה 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Step_Size2__c.field-meta.xml
<CustomField>
    <fullName>Step_Size2__c</fullName>
    <label>גודל מדרגה 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Step_Size3__c.field-meta.xml
<CustomField>
    <fullName>Step_Size3__c</fullName>
    <label>גודל מדרגה 3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Step_Size4__c.field-meta.xml
<CustomField>
    <fullName>Step_Size4__c</fullName>
    <label>גודל מדרגה 4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Submit2__c.field-meta.xml
<CustomField>
    <fullName>Submit2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Token_Id__c.field-meta.xml
<CustomField>
    <fullName>Token_Id__c</fullName>
    <label>Token Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/TotalValueBat__c.field-meta.xml
<CustomField>
    <fullName>TotalValueBat__c</fullName>
    <label>עלות בטריות כוללת</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Trainings__c.field-meta.xml
<CustomField>
    <fullName>Trainings__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>הדרכה</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Trainings__c.NumberOfStudents__c</field>
            <operation>lessThan</operation>
            <valueField>Trainings__c.Max_Students__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Trainings__c</referenceTo>
    <relationshipLabel>כרטיס עסקה</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AcceptPController.cls
public without sharing class AcceptPController {
  Public id Curid;
  Public String Tel;
  Public Account accadd {get;set;}
  Public Transaction_Card__c tcc {get;set;}
  Public Trainings__c tr {get;set;}
  Public String Del {get;set;}
  Public String Ret {get;set;}
  Public String payway {get;set;}
  Public Boolean agr {get;set;}
  Public Boolean err {get;set;}
  public boolean rikushet {get; set;}
  public AcceptPController(ApexPages.StandardController controller)
    {
      agr=false;
      err=false;
      CurId = ApexPages.currentPage().getParameters().get('id');
      Tel = ApexPages.currentPage().getParameters().get('tel');
      tcc=[Select id,Device__c,Program__c,Submit2__c,Manual_Transaction__c,Token_Id__c,CC_Expiration_Date__c,No_of_Payments__c,CityForDelivery__c,DeliveryCost__c,AddressForDelivery__c,Account_Addressing__c,Delivery__c,lithium__c,TotalValueBat__c,Rec_Bat_Amount__c,discount__c,BatAmount__c,Cost_Calculated_Planned_N__c,Maximum_Allowed_Num_Payments__c,Trainings__c,Date_Of_Delivery_Device__c,Scheduled_Return_Date__c,Days_Of_Planned_Service__c,Step_Size1__c,Step_Size2__c,Step_Size3__c,Step_Size4__c,Step_Price1__c,Step_Price2__c,Step_Price3__c,Step_Price4__c,Dollar_Exchange_Rate__c,Affiliate__c from Transaction_Card__c where id=:Curid];
      rikushet = priceController.getRikushet(String.valueof(tcc.Affiliate__c));
      accadd=[select id,Name,PersonEmail,PersonMobilePhone from account where id=:tcc.Account_Addressing__c];
      tr=[select id,name,Date_Time__c from Trainings__c where id=:tcc.Trainings__c];
      Del=tr.Date_Time__c.format();
      Ret=tcc.Scheduled_Return_Date__c.format();
      if(tcc.Manual_Transaction__c==true)
        payway='טלפוני';
      else
        payway='אשראי';
    }
    public PageReference submit()
      {
          err=false;
          if(agr!=true)
            err=true;
          else
          {
            tcc.Submit2__c=true;
            update tcc;
            if(tel=='1')
            {
              String ur='/TelVF';
              PageReference pageRef = new PageReference(ur); //it works
              pageref.setRedirect(true);
              return pageRef;
            }
          }
          return null;
      }
      public PageReference back()
        {
            tcc.Program__c=null;
            update tcc;
            String ur='/pricecalc?id='+Curid+'&device='+tcc.Device__c+'&aff='+tcc.Affiliate__c;
            PageReference pageRef = new PageReference(ur); //it works
            pageref.setRedirect(true);
            return pageRef;
        }
}