force-app/main/default/objects/Transaction_Card__c/Transaction_Card__c.object-meta.xml
<CustomObject>
    <label>כרטיס עסקה</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>שם כרטיס עסקה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>כרטיס עסקה</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Card__c/fields/Account_Passenger__c.field-meta.xml
<CustomField>
    <fullName>Account_Passenger__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>נוסע</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>כרטיס עסקה</relationshipLabel>
    <relationshipName>Account_Passenger</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/IMEI__c.field-meta.xml
<CustomField>
    <fullName>IMEI__c</fullName>
    <formula>Card_Device__r.IMEI__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IMEI</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Pickup_in_Natbag__c.field-meta.xml
<CustomField>
    <fullName>Pickup_in_Natbag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>איסוף בנתב&quot;ג</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Return_in_Natbag__c.field-meta.xml
<CustomField>
    <fullName>Return_in_Natbag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>החזרה בנתב&quot;ג</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/SafeBox_Num__c.field-meta.xml
<CustomField>
    <fullName>SafeBox_Num__c</fullName>
    <label>מספר כספת</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>חדש</fullName>
                <default>true</default>
                <label>חדש</label>
            </value>
            <value>
                <fullName>מילוי טופס</fullName>
            </value>
            <value>
                <fullName>דרוש עידוד</fullName>
            </value>
            <value>
                <fullName>מחכה לאישור טופס</fullName>
            </value>
            <value>
                <fullName>טופס מאושר</fullName>
            </value>
            <value>
                <fullName>הועבר תשלום</fullName>
            </value>
            <value>
                <fullName>הכנת מכשיר</fullName>
            </value>
            <value>
                <fullName>מכשיר מוכן</fullName>
            </value>
            <value>
                <fullName>מסירת מכשיר</fullName>
            </value>
            <value>
                <fullName>טיול</fullName>
            </value>
            <value>
                <fullName>בטיול - נפאל</fullName>
            </value>
            <value>
                <fullName>הארכת טיול</fullName>
            </value>
            <value>
                <fullName>החזרת מכשיר</fullName>
            </value>
            <value>
                <fullName>הסתיים</fullName>
            </value>
            <value>
                <fullName>לא מעוניין</fullName>
            </value>
            <value>
                <fullName>הארכת שירות</fullName>
            </value>
            <value>
                <fullName>צריך לזכות</fullName>
            </value>
            <value>
                <fullName>חיובים בעייתיים</fullName>
            </value>
            <value>
                <fullName>ייעוץ משפחה</fullName>
            </value>
            <value>
                <fullName>בהמתנה למכשיר</fullName>
            </value>
            <value>
                <fullName>לא במלאי</fullName>
            </value>
            <value>
                <fullName>החזרה באיחור</fullName>
            </value>
            <value>
                <fullName>ממתין לאיסוף בנתב&quot;ג</fullName>
            </value>
            <value>
                <fullName>החזרה מנתב&quot;ג</fullName>
            </value>
            <value>
                <fullName>לגבות תשלום נתב&quot;ג</fullName>
            </value>
            <value>
                <fullName>מכשיר נשלח לנתב&quot;ג</fullName>
            </value>
            <value>
                <fullName>בהקפאה - זיכוי</fullName>
            </value>
            <value>
                <fullName>הוזמן משלוח להחזרה HFD</fullName>
            </value>
            <value>
                <fullName>בוטל</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/The_Actual_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>The_Actual_Return_Date__c</fullName>
    <label>תאריך החזרה בפועל</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/NatBagController.cls
public without sharing class NatBagController {
	public String IMEI{get;set;}
	public String VAULT{get;set;}
	public String message{get;set;}
	public boolean err{get;set;}
	public List<Transaction_Card__c> tccs{get;set;}
	public NatBagController() {
	}
	/*public void Departures(){
		message=null;
		err=true;
		tccs=[Select id,Status__c,Account_Passenger__r.Name from Transaction_Card__c where Status__c='ממתין לאיסוף בנתב\"ג' and IMEI__c!=null and IMEI__c=:IMEI and Pickup_in_Natbag__c=true];
		if(tccs.size()>0){
			tccs[0].Status__c = 'טיול';
			update tccs[0];
			err=false;
			IMEI=null;
			message='עודכן בהצלחה! '+tccs[0].Account_Passenger__r.Name+' לקח מכשיר מנתב\"ג.';
		}
		else message='לא נמצא לקוח הממתין למכשיר זה, אנא וודא תקינות IMEI או צור קשר עם המשרדים';
	}*/
	public void Departures(){
		message=null;
		err=true;
		tccs=[Select id,Status__c,Account_Passenger__r.Name from Transaction_Card__c where Status__c='מכשיר מוכן' and IMEI__c!=null and IMEI__c=:IMEI and Pickup_in_Natbag__c=true];
		if(tccs.size()>0){
			tccs[0].Status__c = 'ממתין לאיסוף בנתב\"ג';
			update tccs[0];
			err=false;
			IMEI=null;
			VAULT=null;
			message='עודכן בהצלחה! מכשיר מוכן בנתב\" ג ל'+tccs[0].Account_Passenger__r.Name;
		}
		else message='לא נמצא לקוח הממתין למכשיר זה, אנא וודא תקינות IMEI או צור קשר עם המשרדים';
	}
	public void Vaults(){
		message=null;
		err=true;
		tccs=[Select id,Status__c,SafeBox_Num__c,Account_Passenger__r.Name from Transaction_Card__c where (Status__c='מכשיר מוכן' or Status__c='ממתין לאיסוף בנתב\"ג') and IMEI__c!=null and IMEI__c=:IMEI and Pickup_in_Natbag__c=true];
		if(tccs.size()>0&&VAULT!=null&&VAULT!=''){
			tccs[0].Status__c = 'ממתין לאיסוף בנתב\"ג';
			tccs[0].SafeBox_Num__c = VAULT;
			update tccs[0];
			err=false;
			IMEI=null;
			VAULT=null;
			message='עודכן בהצלחה! מכשיר הועבר לכספת מספר - '+tccs[0].SafeBox_Num__c+' בנתב\" ג ל'+tccs[0].Account_Passenger__r.Name;
		}
		else message='לא נמצא לקוח הממתין למכשיר זה, אנא וודא תקינות IMEI והכסנת ערך בשדה כספת או צור קשר עם המשרדים';
	}
	public void Arrivals(){
		message=null;
		err=true;
		tccs=[Select id,Status__c,The_Actual_Return_Date__c,Account_Passenger__r.Name from Transaction_Card__c where (Status__c='טיול' or Status__c='הארכת טיול' or Status__c='החזרת מכשיר' or Status__c = 'ממתין לאיסוף בנתב\"ג') and IMEI__c!=null and IMEI__c=:IMEI and Return_in_Natbag__c=true];
		if(tccs.size()>0){
			tccs[0].Status__c = 'החזרה מנתב\"ג';
			tccs[0].The_Actual_Return_Date__c=System.Today();
			update tccs[0];
			err=false;
			IMEI=null;
			VAULT=null;
			message='עודכן בהצלחה! '+tccs[0].Account_Passenger__r.Name+' החזיר מכשיר לנתב\"ג.';
		}
		else message='לא נמצא לקוח בטיול עם מכשיר זה, אנא וודא תקינות IMEI או צור קשר עם המשרדים';
	}
}