force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>תשלום</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>תשלומים</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Extended_Service__c.field-meta.xml
<CustomField>
    <fullName>Extended_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>הארכת שירות</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/index__c.field-meta.xml
<CustomField>
    <fullName>index__c</fullName>
    <label>index</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/masof__c.field-meta.xml
<CustomField>
    <fullName>masof__c</fullName>
    <label>masof</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Parent_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Parent_Transaction__c</fullName>
    <label>Parent Transaction</label>
    <referenceTo>Transaction_Card__c</referenceTo>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Payment_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>עסקת מע&quot;מ</label>
    <referenceTo>Payment_Transaction__c</referenceTo>
    <relationshipLabel>תשלומים</relationshipLabel>
    <relationshipName>Payment_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Payment_Transaction_ID__c</fullName>
    <inlineHelpText>מספר אישור מחברת האשראי</inlineHelpText>
    <label>Payment Transaction ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Sum__c.field-meta.xml
<CustomField>
    <fullName>Sum__c</fullName>
    <label>Sum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>חיוב</fullName>
                <default>true</default>
                <label>חיוב</label>
            </value>
            <value>
                <fullName>זיכוי</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/VAT_payment__c.field-meta.xml
<CustomField>
    <fullName>VAT_payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VAT payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <label>עסקת מע&quot;מ</label>
    <nameField>
        <displayFormat>TRN-{0000000}</displayFormat>
        <label>מספר עסקה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>עסקעות מע&quot;מ</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/fields/Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total__c</fullName>
    <label>סה&quot;כ כולל מע&quot;מ</label>
    <summarizedField>Payment_Transaction_line__c.Grand_Total__c</summarizedField>
    <summaryForeignKey>Payment_Transaction_line__c.Payment_Transaction__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>תשלום אשראי</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>עסקעות מע&quot;מ</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>אמצעי תשלום</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>אשראי</fullName>
            </value>
            <value>
                <fullName>מזומן</fullName>
            </value>
            <value>
                <fullName>צ&apos;ק</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Payment_Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Payment_Transaction_ID__c</fullName>
    <formula>Payment__r.Payment_Transaction_ID__c</formula>
    <label>Payment Transaction ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>פתוח</fullName>
                <default>true</default>
                <label>פתוח</label>
            </value>
            <value>
                <fullName>סגור</fullName>
            </value>
            <value>
                <fullName>מבוטל</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Transaction_Card__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>כרטיס עסקת שירות</label>
    <referenceTo>Transaction_Card__c</referenceTo>
    <relationshipLabel>עסקעות מע&quot;מ</relationshipLabel>
    <relationshipName>Payment_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>סוג</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>חיוב</fullName>
            </value>
            <value>
                <fullName>זיכוי</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction_line__c/Payment_Transaction_line__c.object-meta.xml
<CustomObject>
    <label>שורת טרנזקציה</label>
    <nameField>
        <displayFormat>TRL-{0000000}</displayFormat>
        <label>שורת טרנזקציה Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transaction line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction_line__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>הנחה</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction_line__c/fields/Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total__c</fullName>
    <formula>Final_Price__c*Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>סה&quot;כ כולל מע&quot;מ</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction_line__c/fields/Payment_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Payment_Transaction__c</fullName>
    <label>טרנזקציה</label>
    <referenceTo>Payment_Transaction__c</referenceTo>
    <relationshipLabel>Payment Transaction line</relationshipLabel>
    <relationshipName>Payment_Transaction_line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction_line__c/fields/Transaction_Card__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>כרטיס עסקת שירות</label>
    <referenceTo>Transaction_Card__c</referenceTo>
    <relationshipLabel>Payment Transaction line</relationshipLabel>
    <relationshipName>Payment_Transaction_line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/Transaction_Card__c.object-meta.xml
<CustomObject>
    <label>כרטיס עסקה</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>שם כרטיס עסקה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>כרטיס עסקה</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Card__c/fields/Account_Addressing__c.field-meta.xml
<CustomField>
    <fullName>Account_Addressing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>פונה</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>עסקאות</relationshipLabel>
    <relationshipName>Transaction_Card</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/CC_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>CC_Expiration_Date__c</fullName>
    <label>CC Expiration Date</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Cost_Calculated_Planned_N__c.field-meta.xml
<CustomField>
    <fullName>Cost_Calculated_Planned_N__c</fullName>
    <label>עלות מחושבת מתוכנן</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/discount__c.field-meta.xml
<CustomField>
    <fullName>discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>הנחה</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/No_of_Payments__c.field-meta.xml
<CustomField>
    <fullName>No_of_Payments__c</fullName>
    <label>מספר תשלומים בפועל(מכשיר)</label>
    <summaryFilterItems>
        <field>Payment__c.VAT_payment__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Payment__c.Parent_Transaction__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Return_Date_Updated__c.field-meta.xml
<CustomField>
    <fullName>Return_Date_Updated__c</fullName>
    <label>תאריך החזרה מעודכן</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>חדש</fullName>
                <default>true</default>
                <label>חדש</label>
            </value>
            <value>
                <fullName>מילוי טופס</fullName>
            </value>
            <value>
                <fullName>דרוש עידוד</fullName>
            </value>
            <value>
                <fullName>מחכה לאישור טופס</fullName>
            </value>
            <value>
                <fullName>טופס מאושר</fullName>
            </value>
            <value>
                <fullName>הועבר תשלום</fullName>
            </value>
            <value>
                <fullName>הכנת מכשיר</fullName>
            </value>
            <value>
                <fullName>מכשיר מוכן</fullName>
            </value>
            <value>
                <fullName>מסירת מכשיר</fullName>
            </value>
            <value>
                <fullName>טיול</fullName>
            </value>
            <value>
                <fullName>בטיול - נפאל</fullName>
            </value>
            <value>
                <fullName>הארכת טיול</fullName>
            </value>
            <value>
                <fullName>החזרת מכשיר</fullName>
            </value>
            <value>
                <fullName>הסתיים</fullName>
            </value>
            <value>
                <fullName>לא מעוניין</fullName>
            </value>
            <value>
                <fullName>הארכת שירות</fullName>
            </value>
            <value>
                <fullName>צריך לזכות</fullName>
            </value>
            <value>
                <fullName>חיובים בעייתיים</fullName>
            </value>
            <value>
                <fullName>ייעוץ משפחה</fullName>
            </value>
            <value>
                <fullName>בהמתנה למכשיר</fullName>
            </value>
            <value>
                <fullName>לא במלאי</fullName>
            </value>
            <value>
                <fullName>החזרה באיחור</fullName>
            </value>
            <value>
                <fullName>ממתין לאיסוף בנתב&quot;ג</fullName>
            </value>
            <value>
                <fullName>החזרה מנתב&quot;ג</fullName>
            </value>
            <value>
                <fullName>לגבות תשלום נתב&quot;ג</fullName>
            </value>
            <value>
                <fullName>מכשיר נשלח לנתב&quot;ג</fullName>
            </value>
            <value>
                <fullName>בהקפאה - זיכוי</fullName>
            </value>
            <value>
                <fullName>הוזמן משלוח להחזרה HFD</fullName>
            </value>
            <value>
                <fullName>בוטל</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Token_Id__c.field-meta.xml
<CustomField>
    <fullName>Token_Id__c</fullName>
    <label>Token Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ChargeOrRefundController.cls
public without sharing class ChargeOrRefundController {
    Public id Curid;
    Public Payment_Transaction__c ptc {get;set;}
    Public Transaction_Card__c tcc {get;set;}
    Public Payment__c pam {get;set;}
    Public Account accadd {get;set;}
    Public Boolean TokEx {get;set;}
    Public Boolean met {get;set;}
    Public String TokGo {get;set;}
    Public String Half {get;set;}
    Public String Pricepart {get;set;}
    Public String dig {get;set;}
    Public String type {get;set;}
    Public String sfid {get;set;}
    Public String products {get;set;}
    Public decimal Price {get;set;}
    Public Boolean clo {get;set;}
    Public Boolean err {get;set;}
    public ChargeOrRefundController()
    {
      products='';
        err=false;
        clo=true;
        type='';
        TokEx=false;
        met=true;
        CurId = ApexPages.currentPage().getParameters().get('id');
        list <Payment_Transaction__c> ptcl=[select id,name,CurrencyIsoCode,Type__c,Transaction_Card__c,Payment_Method__c,Status__c,Payment__c,Grand_Total__c from Payment_Transaction__c where id=:Curid];
        list <Payment__c> paml=[select id,name,CurrencyIsoCode,masof__c,Extended_Service__c,Parent_Transaction__c,Expiration_Date__c,Payment_Transaction__c,Token__c,VAT_payment__c,Result__c,Sum__c,index__c,Payment_Transaction_ID__c from Payment__c where id=:Curid];
        if(ptcl.size()>0)
        {
            ptc=ptcl[0];
            sfid=ptc.id;
            tcc=[select id,Token_Id__c,CC_Expiration_Date__c,No_of_Payments__c,Account_Addressing__c,discount__c,Return_Date_Updated__c,Cost_Calculated_Planned_N__c,Trainings__c,Date_Of_Delivery_Device__c,Scheduled_Return_Date__c,Days_Of_Planned_Service__c,Step_Size1__c,Step_Size2__c,Step_Size3__c,Step_Size4__c,Step_Price1__c,Step_Price2__c,Step_Price3__c,Step_Price4__c,Dollar_Exchange_Rate__c from Transaction_Card__c where id=:ptc.Transaction_Card__c];
            accadd=[select id,Name,PersonEmail,PersonMobilePhone from account where id=:tcc.Account_Addressing__c];
            type='חיוב';
            if(tcc.Token_id__c!=null)
            {
                TokEx=true;
                string tem=tcc.Token_id__c;
                dig=tem.substring(tem.length()-4);
            }
            if(ptc.Status__c=='סגור')
            {
                clo=false;
            }
            list <Payment_Transaction_line__c> ptls = [select id,CurrencyIsoCode,Grand_Total__c,Quantity__c,Description__c from Payment_Transaction_line__c where Payment_Transaction__c=:ptc.id];
            list <map<string,string>> ptltojson=new list <map<string,string>> ();
            for(Payment_Transaction_line__c ptl: ptls)
            {
              String quan=String.valueOf(ptl.Quantity__c);
              String price=String.valueOf((ptl.Grand_Total__c/ptl.Quantity__c).setscale(2));
              ptltojson.add(new Map<string, string>{
                                'product_name' => ptl.Description__c,
                                'product_quantity' => quan,
                                'product_price' => price
                });
            }
            products=JSON.serialize(ptltojson);
            products=EncodingUtil.urlEncode(products, 'UTF-8');
            System.debug(products);
        }
        if(paml.size()>0)
        {
            pam=paml[0];
            sfid=pam.Payment_Transaction__c;
            type='זיכוי';
            if(pam.Token__c!=null)
            {
                TokEx=true;
                string tem=pam.Token__c;
                dig=tem.substring(tem.length()-4);
            }
            if(pam.Parent_Transaction__c!=null)
            {
            tcc=[select id,Token_Id__c,CC_Expiration_Date__c,No_of_Payments__c,Account_Addressing__c,discount__c,Return_Date_Updated__c,Cost_Calculated_Planned_N__c,Trainings__c,Date_Of_Delivery_Device__c,Scheduled_Return_Date__c,Days_Of_Planned_Service__c,Step_Size1__c,Step_Size2__c,Step_Size3__c,Step_Size4__c,Step_Price1__c,Step_Price2__c,Step_Price3__c,Step_Price4__c,Dollar_Exchange_Rate__c,Manual_Transaction__c from Transaction_Card__c where id=:pam.Parent_Transaction__c];
            accadd=[select id,Name,PersonEmail,PersonMobilePhone from account where id=:tcc.Account_Addressing__c];
            }
        }
        if(type=='חיוב')
            met=false;
    }
    public List<SelectOption> getItems() {
        if(type=='חיוב')
        {
        List<SelectOption> options = new List<SelectOption>();
        if(dig!=null)
            options.add(new SelectOption('True',type+' כרטיס אשראי המסתיים ב'+dig));
        options.add(new SelectOption('False',type+' כרטיס אשראי אחר'));
        return options;
        }
        else
        {
            List<SelectOption> options = new List<SelectOption>();
            options.add(new SelectOption('True',type+' כרטיס אשראי המסתיים ב'+dig));
            return options;
        }
    }
    public List<SelectOption> getPrices() {
        if(type=='זיכוי')
        {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('False','זכה את כל הסכום'));
        options.add(new SelectOption('True','זיכוי חלק מהסכום'));
        return options;
        }
        else
        {
            return null;
        }
    }
    public PageReference submit()
    {
        err=false;
            if(TokGo=='True'&&type=='חיוב'&&ptc.Status__c=='פתוח')
            {
                Http http1=new Http();
                 HttpRequest req1=new HttpRequest();
                 req1.setendpoint('https://secure5.tranzila.com/cgi-bin/tranzila71u.cgi');
                 req1.setmethod('POST');
                 String cur=ptc.CurrencyIsoCode=='USD'?'2':'1';
                 string pos='supplier=magnusintetok&sum='+ptc.Grand_Total__c.setScale(2)+'&expdate='+tcc.CC_Expiration_Date__c+'&currency='+cur+'&TranzilaPW=zJkelm&TranzilaTK='+tcc.Token_id__c+'&cred_type=1&tranmode=A&SF_Transaction_Id='+tcc.id+'&contact='+accadd.name+'&email='+accadd.PersonEmail+'&phone='+accadd.PersonMobilePhone+'&IMaam=0.18&json_purchase_data='+products;
                 req1.setbody(pos);
                 HttpResponse res1;
                 String str='';
                 if(tcc.Token_Id__c!='testspec')
                 {
                 res1 = http1.send(req1);
                 str=res1.getbody();
                    }
                    else
                     str='test&Response=000&ConfirmationCode=100&index=1&';
                system.debug(str);
                system.debug(pos);
                if(str.contains('Response=000'))
                {
                    string con='';
                    string ind='';
                    String [] spl1=str.split('ConfirmationCode=');
                    String [] spl2=str.split('index=');
                    if(spl1[1].contains('&'))
                    {
                        String [] spl3=spl1[1].split('&');
                        con=spl3[0];
                    }
                    else
                        con=spl1[1];
                    if(spl2[1].contains('&'))
                    {
                        String [] spl4=spl2[1].split('&');
                        ind=spl4[0];
                    }
                    else
                        ind=spl2[1];
                     Payment__c pay=new Payment__c();
                        pay.Parent_Transaction__c=ptc.Transaction_Card__c;
                        pay.Expiration_Date__c =tcc.CC_Expiration_Date__c;
                        pay.Token__c=tcc.Token_Id__c;
                        pay.Result__c='000';
                        pay.Payment_Transaction_ID__c=con;
                        pay.Payment_Transaction__c=Curid;
                        pay.index__c=ind;
                        pay.masof__c='magnusintetok';
                        pay.VAT_payment__c=true;
                        TimeZone tz = TimeZone.getTimeZone('Asia/Jerusalem');
                        DateTime localTime = System.now().AddSeconds(tz.getOffset(System.now())/1000);
                        pay.Payment_Time__c=localTime;
                        pay.Sum__c=Ptc.Grand_Total__c;
                        insert pay;
                        ptc.Status__c='סגור';
                        update ptc;
                        String ur='/apex/SuccessVF';
                        PageReference pageRef = new PageReference(ur); //it works
                        pageref.setRedirect(true);
                        return pageRef;
                }
                else
                {
                  String ur='/apex/ERROR';
                        PageReference pageRef = new PageReference(ur); //it works
                        pageref.setRedirect(true);
                        return pageRef;
                }
            }
            if(TokGo=='True'&&type=='זיכוי'&&(half=='False'||half=='True'))
            {
                Http http1=new Http();
                 HttpRequest req1=new HttpRequest();
                 req1.setendpoint('https://secure5.tranzila.com/cgi-bin/tranzila71u.cgi');
                 req1.setmethod('POST');
                 string sup='magnusintetok';
                 string pas='gxMapl';
                 String tokpas='zJkelm';
                 if((pam.VAT_payment__c==false&&tcc.Manual_Transaction__c==false&&pam.Extended_Service__c==false&&pam.masof__c==null)||(pam.VAT_payment__c==true&&tcc.Token_Id__c!=pam.Token__c&&pam.masof__c==null)||(pam.masof__c=='magnusinte'))
                 {
                     sup='magnusinte';
                     pas='nVRS9w';
                     tokpas='B6l58e';
                 }
                 if(half=='False')
                 {
                price=pam.Sum__c;
                String cur=pam.CurrencyIsoCode=='USD'?'2':'1';
                String pos='supplier='+sup+'&sum='+pam.Sum__c.setScale(2)+'&expdate='+pam.Expiration_Date__c+'&currency='+cur+'&TranzilaPW='+tokpas+'&TranzilaTK='+pam.Token__c+'&cred_type=1&tranmode=C'+pam.index__c+'&authnr='+pam.Payment_Transaction_ID__c+'&CreditPass='+pas+'&SF_Transaction_Id='+tcc.id+'&contact='+accadd.name+'&email='+accadd.PersonEmail+'&phone='+accadd.PersonMobilePhone;
                 req1.setbody(pos);
                 HttpResponse res1;
                 String str='';
                 if(pam.Token__c!='testspec')
                 {
                 res1 = http1.send(req1);
                 str=res1.getbody();
                    }
                    else
                     str='test&Response=000&ConfirmationCode=100&index=1&';
                system.debug(str);
                system.debug(pos);
                if(str.contains('Response=000'))
                {
                    string con='';
                    string ind='';
                    String [] spl1=str.split('ConfirmationCode=');
                    String [] spl2=str.split('index=');
                    if(spl1[1].contains('&'))
                    {
                        String [] spl3=spl1[1].split('&');
                        con=spl3[0];
                    }
                    else
                        con=spl1[1];
                    if(spl2[1].contains('&'))
                    {
                        String [] spl4=spl2[1].split('&');
                        ind=spl4[0];
                    }
                    else
                        ind=spl2[1];
                    Payment__c payn=new Payment__c();
                       payn.Parent_Transaction__c=pam.Parent_Transaction__c;
                       payn.Expiration_Date__c =pam.Expiration_Date__c;
                       payn.Token__c=pam.Token__c;
                       payn.Payment_Transaction__c=pam.Payment_Transaction__c;
                       payn.Result__c='000';
                       payn.Payment_Transaction_ID__c=con;
                       payn.masof__c=sup;
                       payn.index__c=ind;
                       payn.VAT_payment__c=pam.VAT_payment__c;
                       TimeZone tz = TimeZone.getTimeZone('Asia/Jerusalem');
                       DateTime localTime = System.now().AddSeconds(tz.getOffset(System.now())/1000);
                       payn.Payment_Time__c=localTime;
                       payn.Sum__c=price*(-1);
                       insert payn;
                       String ur='/apex/SuccessVF';
                       PageReference pageRef = new PageReference(ur); //it works
                       pageref.setRedirect(true);
                       return pageRef;
                }
                else
                {
                  String ur='/apex/ERROR';
                        PageReference pageRef = new PageReference(ur); //it works
                        pageref.setRedirect(true);
                        return pageRef;
                }
            }
                if(half=='True'&&Pricepart!=null&&Pricepart!=''&&Decimal.valueOf(Pricepart)<=pam.sum__c&&Decimal.valueOf(Pricepart)>0)
                {
                    price=Decimal.valueOf(Pricepart);
                 String cur=pam.CurrencyIsoCode=='USD'?'2':'1';
                String pos='supplier='+sup+'&sum='+Pricepart+'&expdate='+pam.Expiration_Date__c+'&currency='+cur+'&TranzilaPW='+tokpas+'&TranzilaTK='+pam.Token__c+'&cred_type=1&tranmode=C'+pam.index__c+'&authnr='+pam.Payment_Transaction_ID__c+'&CreditPass='+pas+'&SF_Transaction_Id='+tcc.id+'&contact='+accadd.name+'&email='+accadd.PersonEmail+'&phone='+accadd.PersonMobilePhone;
                 req1.setbody(pos);
                 HttpResponse res1;
                 String str='';
                 if(pam.Token__c!='testspec')
                 {
                 res1 = http1.send(req1);
                 str=res1.getbody();
                    }
                    else
                     str='test&Response=000&ConfirmationCode=100&index=1&';
                system.debug(str);
                system.debug(pos);
                if(str.contains('Response=000'))
                {
                    string con='';
                    string ind='';
                    String [] spl1=str.split('ConfirmationCode=');
                    String [] spl2=str.split('index=');
                    if(spl1[1].contains('&'))
                    {
                        String [] spl3=spl1[1].split('&');
                        con=spl3[0];
                    }
                    else
                        con=spl1[1];
                    if(spl2[1].contains('&'))
                    {
                        String [] spl4=spl2[1].split('&');
                        ind=spl4[0];
                    }
                    else
                        ind=spl2[1];
                    Payment__c payn=new Payment__c();
                       payn.Parent_Transaction__c=pam.Parent_Transaction__c;
                       payn.Expiration_Date__c =pam.Expiration_Date__c;
                       payn.Token__c=pam.Token__c;
                       payn.Payment_Transaction__c=pam.Payment_Transaction__c;
                       payn.Result__c='000';
                       payn.masof__c=sup;
                       payn.Payment_Transaction_ID__c=con;
                       payn.index__c=ind;
                       payn.VAT_payment__c=pam.VAT_payment__c;
                       TimeZone tz = TimeZone.getTimeZone('Asia/Jerusalem');
                       DateTime localTime = System.now().AddSeconds(tz.getOffset(System.now())/1000);
                       payn.Payment_Time__c=localTime;
                       payn.Sum__c=price*(-1);
                       insert payn;
                       String ur='/apex/SuccessVF';
                       PageReference pageRef = new PageReference(ur); //it works
                       pageref.setRedirect(true);
                       return pageRef;
                }
                else
                {
                  String ur='/apex/ERROR';
                        PageReference pageRef = new PageReference(ur); //it works
                        pageref.setRedirect(true);
                        return pageRef;
                }
            }
            else
                err=true;
            }
        return null;
    }
}