force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>תשלום</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>תשלומים</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/index__c.field-meta.xml
<CustomField>
    <fullName>index__c</fullName>
    <label>index</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/masof__c.field-meta.xml
<CustomField>
    <fullName>masof__c</fullName>
    <label>masof</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Parent_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Parent_Transaction__c</fullName>
    <label>Parent Transaction</label>
    <referenceTo>Transaction_Card__c</referenceTo>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Payment_Transaction_ID__c</fullName>
    <inlineHelpText>מספר אישור מחברת האשראי</inlineHelpText>
    <label>Payment Transaction ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/Transaction_Card__c.object-meta.xml
<CustomObject>
    <label>כרטיס עסקה</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>שם כרטיס עסקה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>כרטיס עסקה</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Card__c/fields/Account_Addressing__c.field-meta.xml
<CustomField>
    <fullName>Account_Addressing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>פונה</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>עסקאות</relationshipLabel>
    <relationshipName>Transaction_Card</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/AddressForDelivery__c.field-meta.xml
<CustomField>
    <fullName>AddressForDelivery__c</fullName>
    <label>כתובת למשלוח</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/BatAmount__c.field-meta.xml
<CustomField>
    <fullName>BatAmount__c</fullName>
    <defaultValue>10</defaultValue>
    <label>מחיר סוללה</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/CC_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>CC_Expiration_Date__c</fullName>
    <label>CC Expiration Date</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/CityForDelivery__c.field-meta.xml
<CustomField>
    <fullName>CityForDelivery__c</fullName>
    <label>ישוב למשלוח</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Cost_Calculated_Planned_N__c.field-meta.xml
<CustomField>
    <fullName>Cost_Calculated_Planned_N__c</fullName>
    <label>עלות מחושבת מתוכנן</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/CreditAmount__c.field-meta.xml
<CustomField>
    <fullName>CreditAmount__c</fullName>
    <label>סכום לחיוב אשראי</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Date_Of_Delivery_Device__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Delivery_Device__c</fullName>
    <label>תאריך איסוף המכשיר</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Days_Of_Planned_Service__c.field-meta.xml
<CustomField>
    <fullName>Days_Of_Planned_Service__c</fullName>
    <formula>Scheduled_Return_Date__c -Date_Of_Delivery_Device__c + 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>מס&apos; ימי שירות מתוכנן</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <defaultValue>false</defaultValue>
    <label>משלוח</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/DeliveryCost__c.field-meta.xml
<CustomField>
    <fullName>DeliveryCost__c</fullName>
    <label>עלות משלוח</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/discount__c.field-meta.xml
<CustomField>
    <fullName>discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>הנחה</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Dollar_Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>Dollar_Exchange_Rate__c</fullName>
    <defaultValue>3.55</defaultValue>
    <label>שער דולר</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/lithium__c.field-meta.xml
<CustomField>
    <fullName>lithium__c</fullName>
    <defaultValue>1</defaultValue>
    <label>כמות סוללות ליתיום</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Manual_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Manual_Transaction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>עסקה ידנית</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/No_of_Payments__c.field-meta.xml
<CustomField>
    <fullName>No_of_Payments__c</fullName>
    <label>מספר תשלומים בפועל(מכשיר)</label>
    <summaryFilterItems>
        <field>Payment__c.VAT_payment__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Payment__c.Parent_Transaction__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Payee_id__c.field-meta.xml
<CustomField>
    <fullName>Payee_id__c</fullName>
    <label>ת.ז</label>
    <length>9</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Rec_Bat_Amount__c.field-meta.xml
<CustomField>
    <fullName>Rec_Bat_Amount__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Rec Bat Amount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Registration_Fees__c.field-meta.xml
<CustomField>
    <fullName>Registration_Fees__c</fullName>
    <defaultValue>0</defaultValue>
    <label>דמי הרשמה</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Scheduled_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Return_Date__c</fullName>
    <label>תאריך החזרה מתוכנן</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>חדש</fullName>
                <default>true</default>
                <label>חדש</label>
            </value>
            <value>
                <fullName>מילוי טופס</fullName>
            </value>
            <value>
                <fullName>דרוש עידוד</fullName>
            </value>
            <value>
                <fullName>מחכה לאישור טופס</fullName>
            </value>
            <value>
                <fullName>טופס מאושר</fullName>
            </value>
            <value>
                <fullName>הועבר תשלום</fullName>
            </value>
            <value>
                <fullName>הכנת מכשיר</fullName>
            </value>
            <value>
                <fullName>מכשיר מוכן</fullName>
            </value>
            <value>
                <fullName>מסירת מכשיר</fullName>
            </value>
            <value>
                <fullName>טיול</fullName>
            </value>
            <value>
                <fullName>בטיול - נפאל</fullName>
            </value>
            <value>
                <fullName>הארכת טיול</fullName>
            </value>
            <value>
                <fullName>החזרת מכשיר</fullName>
            </value>
            <value>
                <fullName>הסתיים</fullName>
            </value>
            <value>
                <fullName>לא מעוניין</fullName>
            </value>
            <value>
                <fullName>הארכת שירות</fullName>
            </value>
            <value>
                <fullName>צריך לזכות</fullName>
            </value>
            <value>
                <fullName>חיובים בעייתיים</fullName>
            </value>
            <value>
                <fullName>ייעוץ משפחה</fullName>
            </value>
            <value>
                <fullName>בהמתנה למכשיר</fullName>
            </value>
            <value>
                <fullName>לא במלאי</fullName>
            </value>
            <value>
                <fullName>החזרה באיחור</fullName>
            </value>
            <value>
                <fullName>ממתין לאיסוף בנתב&quot;ג</fullName>
            </value>
            <value>
                <fullName>החזרה מנתב&quot;ג</fullName>
            </value>
            <value>
                <fullName>לגבות תשלום נתב&quot;ג</fullName>
            </value>
            <value>
                <fullName>מכשיר נשלח לנתב&quot;ג</fullName>
            </value>
            <value>
                <fullName>בהקפאה - זיכוי</fullName>
            </value>
            <value>
                <fullName>הוזמן משלוח להחזרה HFD</fullName>
            </value>
            <value>
                <fullName>בוטל</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Step_Price1__c.field-meta.xml
<CustomField>
    <fullName>Step_Price1__c</fullName>
    <label>מחיר מדרגה 1</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Step_Price2__c.field-meta.xml
<CustomField>
    <fullName>Step_Price2__c</fullName>
    <label>מחיר מדרגה 2</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Step_Price3__c.field-meta.xml
<CustomField>
    <fullName>Step_Price3__c</fullName>
    <label>מחיר מדרגה 3</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Step_Price4__c.field-meta.xml
<CustomField>
    <fullName>Step_Price4__c</fullName>
    <label>מחיר מדרגה 4</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Step_Size1__c.field-meta.xml
<CustomField>
    <fullName>Step_Size1__c</fullName>
    <label>גודל מדרגה 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Step_Size2__c.field-meta.xml
<CustomField>
    <fullName>Step_Size2__c</fullName>
    <label>גודל מדרגה 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Step_Size3__c.field-meta.xml
<CustomField>
    <fullName>Step_Size3__c</fullName>
    <label>גודל מדרגה 3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Step_Size4__c.field-meta.xml
<CustomField>
    <fullName>Step_Size4__c</fullName>
    <label>גודל מדרגה 4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Token_Id__c.field-meta.xml
<CustomField>
    <fullName>Token_Id__c</fullName>
    <label>Token Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/TotalValueBat__c.field-meta.xml
<CustomField>
    <fullName>TotalValueBat__c</fullName>
    <label>עלות בטריות כוללת</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Trainings__c.field-meta.xml
<CustomField>
    <fullName>Trainings__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>הדרכה</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Trainings__c.NumberOfStudents__c</field>
            <operation>lessThan</operation>
            <valueField>Trainings__c.Max_Students__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Trainings__c</referenceTo>
    <relationshipLabel>כרטיס עסקה</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Transaction_expected_num_payments__c.field-meta.xml
<CustomField>
    <fullName>Transaction_expected_num_payments__c</fullName>
    <defaultValue>1</defaultValue>
    <label>מס&apos; תשלומים בעסקה</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Transaction_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Start_Date__c</fullName>
    <label>תאריך התחלה לתשלום</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/FuturePaySend.cls
public without sharing class FuturePaySend
{
    @Future(callout=true)
    public static void SendPay(id tcl)
    {
      Transaction_Card__c tcc =[Select id,CreditAmount__c,Transaction_Start_Date__c,Transaction_expected_num_payments__c,Payee_id__c,Manual_Transaction__c,Token_Id__c,CC_Expiration_Date__c,No_of_Payments__c,CityForDelivery__c,DeliveryCost__c,AddressForDelivery__c,Account_Addressing__c,Delivery__c,lithium__c,TotalValueBat__c,Rec_Bat_Amount__c,discount__c,BatAmount__c,Registration_Fees__c,Cost_Calculated_Planned_N__c,Trainings__c,Date_Of_Delivery_Device__c,Scheduled_Return_Date__c,Days_Of_Planned_Service__c,Step_Size1__c,Step_Size2__c,Step_Size3__c,Step_Size4__c,Step_Price1__c,Step_Price2__c,Step_Price3__c,Step_Price4__c,Dollar_Exchange_Rate__c from Transaction_Card__c where Status__c!='לא מעוניין' and id=:tcl];
      Account accadd=[select id,Name,PersonEmail,PersonMobilePhone from account where id=:tcc.Account_Addressing__c];
      string pos='';
        decimal npay=tcc.Transaction_expected_num_payments__c-1;
        if(npay>0)
        {
          decimal pp2=tcc.CreditAmount__c/tcc.Transaction_expected_num_payments__c;
          pp2=pp2.setScale(2);
          decimal pp1=tcc.CreditAmount__c-(pp2*(npay));
          pos='supplier=magnusintetok&sum='+tcc.CreditAmount__c+'&expdate='+tcc.CC_Expiration_Date__c+'&currency=1&TranzilaPW=zJkelm&TranzilaTK='+tcc.Token_Id__c+'&cred_type=8&tranmode=A&fpay='+pp1+'&spay='+pp2+'&npay='+npay+'&SF_Transaction_Id='+tcc.id+'&contact='+accadd.name+'&email='+accadd.PersonEmail+'&phone='+accadd.PersonMobilePhone+'&IMaam=0';
        }
        else
          pos='supplier=magnusintetok&sum='+tcc.CreditAmount__c+'&expdate='+tcc.CC_Expiration_Date__c+'&currency=1&TranzilaPW=zJkelm&TranzilaTK='+tcc.Token_Id__c+'&cred_type=1&tranmode=A&SF_Transaction_Id='+tcc.id+'&contact='+accadd.name+'&email='+accadd.PersonEmail+'&phone='+accadd.PersonMobilePhone+'&IMaam=0';
        Http http1=new Http();
        HttpRequest req1=new HttpRequest();
        req1.setendpoint('https://secure5.tranzila.com/cgi-bin/tranzila71u.cgi');
        req1.setmethod('POST');
        system.debug(pos);
        req1.setbody(pos);
        HttpResponse res1;
        String str='';
        if(tcc.Token_id__c!='testspec')
        {
        res1 = http1.send(req1);
        str=res1.getbody();
        }
        else
        {
        str='test&Response=000&ConfirmationCode=100&index=1&';
        }
        system.debug(str);
        if(str.contains('Response=000'))
        {
          string con='';
          string ind='';
          String [] spl1=str.split('ConfirmationCode=');
          String [] spl2=str.split('index=');
          if(spl1[1].contains('&'))
          {
              String [] spl3=spl1[1].split('&');
              con=spl3[0];
          }
          else
              con=spl1[1];
          if(spl2[1].contains('&'))
          {
              String [] spl4=spl2[1].split('&');
              ind=spl4[0];
          }
          else
              ind=spl2[1];
            Payment__c pay=new Payment__c();
            pay.Parent_Transaction__c=tcc.id;
            pay.Expiration_Date__c =tcc.CC_Expiration_Date__c;
            pay.Token__c=tcc.Token_Id__c;
            pay.Payment_Transaction_ID__c=con;
            pay.masof__c='magnusintetok';
            pay.index__c=ind;
            pay.Result__c='000';
            TimeZone tz = TimeZone.getTimeZone('Asia/Jerusalem');
            DateTime localTime = System.now().AddSeconds(tz.getOffset(System.now())/1000);
            pay.Payment_Time__c=localTime;
            pay.Sum__c=tcc.CreditAmount__c;
            insert pay;
        }
        list<Transaction_Card__c> tccs =[Select id,Transaction_Start_Date__c,Payee_id__c,Manual_Transaction__c,Token_Id__c,CC_Expiration_Date__c,No_of_Payments__c,CityForDelivery__c,DeliveryCost__c,AddressForDelivery__c,Account_Addressing__c,Delivery__c,lithium__c,TotalValueBat__c,Rec_Bat_Amount__c,discount__c,BatAmount__c,Registration_Fees__c,Cost_Calculated_Planned_N__c,Trainings__c,Date_Of_Delivery_Device__c,Scheduled_Return_Date__c,Days_Of_Planned_Service__c,Step_Size1__c,Step_Size2__c,Step_Size3__c,Step_Size4__c,Step_Price1__c,Step_Price2__c,Step_Price3__c,Step_Price4__c,Dollar_Exchange_Rate__c from Transaction_Card__c where No_of_payments__c=0 and Manual_Transaction__c=true and Token_Id__c!=null and Transaction_Start_Date__c=:system.today() and Status__c!='לא מעוניין' and id!=:tcc.id];
        if(tccs.size()>0)
        {
            ID jobID = System.enqueueJob(new QueFuturePay(tccs[0].id));
        }
    }
}