force-app/main/default/objects/Card_Device__c/Card_Device__c.object-meta.xml
<CustomObject>
    <label>כרטיס מכשיר</label>
    <nameField>
        <displayFormat>DEV-{000000000}</displayFormat>
        <label>מכשיר</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>כרטיס מכשיר</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Device__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>כרטיס מכשיר</relationshipLabel>
    <relationshipName>Card_Device</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card_Device__c/fields/model__c.field-meta.xml
<CustomField>
    <fullName>model__c</fullName>
    <label>דגם</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SE+</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>SAT_Phone</fullName>
            </value>
            <value>
                <fullName>Mini</fullName>
            </value>
            <value>
                <fullName>סים לוויני</fullName>
            </value>
            <value>
                <fullName>MINI 2</fullName>
            </value>
            <value>
                <fullName>GPS MAP 66i</fullName>
            </value>
            <value>
                <fullName>Messenger</fullName>
            </value>
            <value>
                <fullName>דגמים</fullName>
                <isActive>false</isActive>
                <label>דגמים</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/Transaction_Card__c.object-meta.xml
<CustomObject>
    <label>כרטיס עסקה</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>שם כרטיס עסקה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>כרטיס עסקה</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Card__c/fields/Account_Passenger__c.field-meta.xml
<CustomField>
    <fullName>Account_Passenger__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>נוסע</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>כרטיס עסקה</relationshipLabel>
    <relationshipName>Account_Passenger</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Card_Device__c.field-meta.xml
<CustomField>
    <fullName>Card_Device__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>כרטיס מכשיר</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Card_Device__c.Inventory__c</field>
            <operation>equals</operation>
            <value>במלאי</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Card_Device__c</referenceTo>
    <relationshipLabel>כרטיס עסקה</relationshipLabel>
    <relationshipName>Transaction_Card</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Device_Recipient__c.field-meta.xml
<CustomField>
    <fullName>Device_Recipient__c</fullName>
    <label>מקבל המכשיר</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Signature__c.field-meta.xml
<CustomField>
    <fullName>Signature__c</fullName>
    <label>חתימת מקבל המכשיר</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Terms_conditions_accepted__c.field-meta.xml
<CustomField>
    <fullName>Terms_conditions_accepted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>הסכים לתנאי השירות</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CustomerInvoiceControllerAccept.cls
public without sharing class CustomerInvoiceControllerAccept {
	public String signatureData {set; get;}
		public String signaturepic {set; get;}
        public String signatureid {set; get;}
        public String dear {set; get;}
        public String dear2 {set; get;}
		public id Curid{get;set;}
		public Transaction_card__c tcc{get;set;}
        public Transaction_card__c uptcc{get;set;}
        public Document doc{get;set;}
    public CustomerInvoiceControllerAccept(ApexPages.StandardController controller)
    {
        dear='';
        signatureid=ApexPages.currentPage().getParameters().get('sigpic');
        signaturepic='';
        if(signatureid!=null)
        {
            doc=[select id,body from document where id=:signatureid];
            signaturepic='/servlet/servlet.FileDownload?file='+signatureid;
        }
        Curid=ApexPages.currentPage().getParameters().get('id');
        tcc=[select id,Signature__c,name,Card_Device__r.model__c,Terms_conditions_accepted__c,Device_recipient__c,Account_Passenger__r.Name from Transaction_card__c where id=:Curid];
        uptcc=tcc;
        Pattern p = Pattern.compile('[a-zA-Z]+');
        Pattern ps = Pattern.compile('[a-zA-Z]+ [a-zA-Z]+');
        Boolean a = p.matcher(uptcc.Device_recipient__c).matches();
        Boolean b = ps.matcher(uptcc.Device_recipient__c).matches();
        Boolean c = p.matcher(tcc.Account_Passenger__r.Name).matches();
        Boolean d = ps.matcher(tcc.Account_Passenger__r.Name).matches();
        if(!b&&!a)
            uptcc.Device_recipient__c=Reverse(uptcc.Device_recipient__c);
        if(!d&&!c)
        {
            dear='לכבוד : '+tcc.Account_Passenger__r.Name;
            dear2=Reverse(tcc.Account_Passenger__r.Name)+' : דובכל';
        }
            else
            {
            dear=tcc.Account_Passenger__r.Name+' : לכבוד';
            dear2=tcc.Account_Passenger__r.Name+' : דובכל';
        }
    }
		private String Reverse(String str) {
		String reversed = '';
		Integer len = str.length();

		for(Integer i = len - 1; i >= 0; i--) {
			reversed += str.substring(i, i + 1);
		}

		return reversed;
	}
    public pagereference GeneratePDF(){
        pagereference Pg = Page.CustomerInvoice2;
        if(signatureid!=null)
            Pg.getParameters().put('sigpic', doc.id);
        attachment at = new Attachment();
        try
        {
        	Blob pdf1 = pg.getcontentASPDF();
            at.Body=pdf1;
        }
        catch(exception e)
        {
            at.body=Blob.valueOf('Unit Test Attachment Body');
        }
        at.OwnerId = UserInfo.getUserId();
        at.ParentId = tcc.Id;
        at.Name=tcc.Name+'.pdf';
        at.ContentType = 'application/pdf';
        insert at;
        if(signatureid!=null)
            delete doc;
        String ur='/apex/InvoiceEmail?id='+tcc.id+'&Atid='+at.id;
        PageReference pageRef = new PageReference(ur);
        pageRef.setRedirect(True);
        return pageRef;
    }
    public pagereference Back(){
        if(signatureid!=null)
        {
            try{
                delete doc;
            }
            catch (exception e){}
        }
        String ur='/apex/CustomerInvoice?id='+tcc.id;
        PageReference newPage = new PageReference(ur);
        newPage.setRedirect(true);
        return newPage;
    }
}