force-app/main/default/objects/Card_Device__c/Card_Device__c.object-meta.xml
<CustomObject>
    <label>כרטיס מכשיר</label>
    <nameField>
        <displayFormat>DEV-{000000000}</displayFormat>
        <label>מכשיר</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>כרטיס מכשיר</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Device__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>מצב</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>לתיקון</fullName>
            </value>
            <value>
                <fullName>מושבת</fullName>
            </value>
            <value>
                <fullName>נגנב</fullName>
            </value>
            <value>
                <fullName>פרזנטור</fullName>
            </value>
            <value>
                <fullName>מוכן ללקוח</fullName>
                <default>true</default>
                <label>מוכן ללקוח</label>
            </value>
            <value>
                <fullName>אצל לקוח</fullName>
            </value>
            <value>
                <fullName>תקין</fullName>
            </value>
            <value>
                <fullName>לבדיקה</fullName>
            </value>
            <value>
                <fullName>הוחזר</fullName>
                <isActive>false</isActive>
                <label>הוחזר</label>
            </value>
            <value>
                <fullName>נגרע</fullName>
                <isActive>false</isActive>
                <label>נגרע</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/Transaction_Card__c.object-meta.xml
<CustomObject>
    <label>כרטיס עסקה</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>שם כרטיס עסקה</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>כרטיס עסקה</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Card__c/fields/Account_Addressing__c.field-meta.xml
<CustomField>
    <fullName>Account_Addressing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>פונה</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>עסקאות</relationshipLabel>
    <relationshipName>Transaction_Card</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Account_Passenger__c.field-meta.xml
<CustomField>
    <fullName>Account_Passenger__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>נוסע</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>כרטיס עסקה</relationshipLabel>
    <relationshipName>Account_Passenger</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Card_Device__c.field-meta.xml
<CustomField>
    <fullName>Card_Device__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>כרטיס מכשיר</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Card_Device__c.Inventory__c</field>
            <operation>equals</operation>
            <value>במלאי</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Card_Device__c</referenceTo>
    <relationshipLabel>כרטיס עסקה</relationshipLabel>
    <relationshipName>Transaction_Card</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/CC_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>CC_Expiration_Date__c</fullName>
    <label>CC Expiration Date</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Cost_Calculated_Planned_N__c.field-meta.xml
<CustomField>
    <fullName>Cost_Calculated_Planned_N__c</fullName>
    <label>עלות מחושבת מתוכנן</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Date_Of_Delivery_Device__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Delivery_Device__c</fullName>
    <label>תאריך איסוף המכשיר</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Date_Of_Return__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Return__c</fullName>
    <label>תאריך חזרה לארץ</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Device__c.field-meta.xml
<CustomField>
    <fullName>Device__c</fullName>
    <label>מכשיר</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>מכשיר A</label>
            </value>
            <value>
                <fullName>SE+</fullName>
                <label>מכשיר SE+</label>
            </value>
            <value>
                <fullName>Mini</fullName>
                <label>מכשיר  mini</label>
            </value>
            <value>
                <fullName>MINI 2</fullName>
            </value>
            <value>
                <fullName>A - מטיילים בחול</fullName>
            </value>
            <value>
                <fullName>A - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>MINI - מטיילים בחול</fullName>
            </value>
            <value>
                <fullName>MINI - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>Iridium 9555</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>Messenger</fullName>
            </value>
            <value>
                <fullName>MINI 2 - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>MINI 2 - מטיילים בחו&quot;ל</fullName>
            </value>
            <value>
                <fullName>Messenger - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>Messenger - מטיילים בחו&quot;ל</fullName>
            </value>
            <value>
                <fullName>SE+ - מטיילים בארץ</fullName>
            </value>
            <value>
                <fullName>SE+ - מטיילים בחו&quot;ל</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/No_of_Payments__c.field-meta.xml
<CustomField>
    <fullName>No_of_Payments__c</fullName>
    <label>מספר תשלומים בפועל(מכשיר)</label>
    <summaryFilterItems>
        <field>Payment__c.VAT_payment__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Payment__c.Parent_Transaction__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Record_Type_Name_Text__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name_Text__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type Name Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Scheduled_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Return_Date__c</fullName>
    <label>תאריך החזרה מתוכנן</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>סטטוס</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>חדש</fullName>
                <default>true</default>
                <label>חדש</label>
            </value>
            <value>
                <fullName>מילוי טופס</fullName>
            </value>
            <value>
                <fullName>דרוש עידוד</fullName>
            </value>
            <value>
                <fullName>מחכה לאישור טופס</fullName>
            </value>
            <value>
                <fullName>טופס מאושר</fullName>
            </value>
            <value>
                <fullName>הועבר תשלום</fullName>
            </value>
            <value>
                <fullName>הכנת מכשיר</fullName>
            </value>
            <value>
                <fullName>מכשיר מוכן</fullName>
            </value>
            <value>
                <fullName>מסירת מכשיר</fullName>
            </value>
            <value>
                <fullName>טיול</fullName>
            </value>
            <value>
                <fullName>בטיול - נפאל</fullName>
            </value>
            <value>
                <fullName>הארכת טיול</fullName>
            </value>
            <value>
                <fullName>החזרת מכשיר</fullName>
            </value>
            <value>
                <fullName>הסתיים</fullName>
            </value>
            <value>
                <fullName>לא מעוניין</fullName>
            </value>
            <value>
                <fullName>הארכת שירות</fullName>
            </value>
            <value>
                <fullName>צריך לזכות</fullName>
            </value>
            <value>
                <fullName>חיובים בעייתיים</fullName>
            </value>
            <value>
                <fullName>ייעוץ משפחה</fullName>
            </value>
            <value>
                <fullName>בהמתנה למכשיר</fullName>
            </value>
            <value>
                <fullName>לא במלאי</fullName>
            </value>
            <value>
                <fullName>החזרה באיחור</fullName>
            </value>
            <value>
                <fullName>ממתין לאיסוף בנתב&quot;ג</fullName>
            </value>
            <value>
                <fullName>החזרה מנתב&quot;ג</fullName>
            </value>
            <value>
                <fullName>לגבות תשלום נתב&quot;ג</fullName>
            </value>
            <value>
                <fullName>מכשיר נשלח לנתב&quot;ג</fullName>
            </value>
            <value>
                <fullName>בהקפאה - זיכוי</fullName>
            </value>
            <value>
                <fullName>הוזמן משלוח להחזרה HFD</fullName>
            </value>
            <value>
                <fullName>בוטל</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/Token_Id__c.field-meta.xml
<CustomField>
    <fullName>Token_Id__c</fullName>
    <label>Token Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Card__c/fields/TookFine__c.field-meta.xml
<CustomField>
    <fullName>TookFine__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TookFine</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NepalFinesScheduler.cls
public without sharing class NepalFinesScheduler implements Schedulable {
  public void execute(SchedulableContext sc){
		/*List <Transaction_Card__c> tcs=[Select id,TookFine__c,CurrencyIsoCode,Device__c,Card_Device__c,Date_Of_Return__c,Token_Id__c,CC_Expiration_Date__c,No_of_Payments__c,Cost_Calculated_Planned_N__c,Date_Of_Delivery_Device__c,Scheduled_Return_Date__c,CreatedDate,Account_Passenger__r.Phone,Account_Addressing__r.PersonMobilePhone,Account_Addressing__r.Phone,Account_Addressing__r.Name,Account_Addressing__r.PersonEmail from Transaction_Card__c where TookFine__c=false And Status__c='בטיול - נפאל' And Record_Type_Name_Text__c='נפאל' and Scheduled_Return_Date__c<:System.Today().AddDays(-30)];
		if(tcs.Size()>0)
			ID jobID = System.enqueueJob(new NepalFinesQueue(tcs));*/
	}
}